version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    mem_limit: 700m
    cpus: 0.5
    environment:
      MYSQL_ROOT_PASSWORD: strong_root_password
      MYSQL_DATABASE: userdb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  service-registry:
    container_name: service-registry
    image: chetan0172/service-registry:${IMAGE_TAG}
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    mem_limit: 600m
    cpus: 0.5
    networks:
      - backend

  api-gateway:
    container_name: api-gateway
    image: chetan0172/api-gateway:${IMAGE_TAG}
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    mem_limit: 600m
    cpus: 0.5
    ports:
      - "127.0.0.1:8080:8080"   # 🔥 Only accessible locally
    depends_on:
      - service-registry
    networks:
      - backend

  user-service:
    container_name: user-service
    image: chetan0172/user-service:${IMAGE_TAG}
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    mem_limit: 600m
    cpus: 0.5
    depends_on:
      mysql:
        condition: service_healthy
      service-registry:
        condition: service_started
    networks:
      - backend

  product-service:
    container_name: product-service
    image: chetan0172/product-service:${IMAGE_TAG}
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    mem_limit: 600m
    cpus: 0.5
    depends_on:
      mysql:
        condition: service_healthy
      service-registry:
        condition: service_started
    networks:
      - backend

  order-service:
    container_name: order-service
    image: chetan0172/order-service:${IMAGE_TAG}
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    mem_limit: 600m
    cpus: 0.5
    depends_on:
      - service-registry
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-data: