name: CD - Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /opt/microservices

            export IMAGE_TAG=${{ github.sha }}

            echo "Using image tag: $IMAGE_TAG"

            docker-compose pull

            docker-compose down
            docker-compose up -d --force-recreate

            docker image prune -af