name: CD - Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /opt/microservices

            echo "Pull latest code"
            git pull origin main

            echo "Set IMAGE_TAG"
            export IMAGE_TAG=${{ github.sha }}

            echo "Pull latest images"
            docker compose pull

            echo "Ensure Redis is running"
            docker compose up -d redis

            echo "Recreate all services with new tag"
            docker compose up -d --force-recreate