name: CI with SonarQube

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Analyze
        run: mvn clean verify sonar:sonar \
          -Dsonar.projectKey=microservices-parent \
          -Dsonar.host.url=${{ secrets.http://http://3.227.117.10:9000 }} \
          -Dsonar.login=${{ secrets.squ_e69efc82fa7a344d17177e4ab9728855b1a0b0dc }}