name: Build and Push Docker Images

on:
  push:
    branches:
      - dev
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push service-registry
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/service-registry:latest -f service-registry/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/service-registry:latest

      - name: Build and Push api-gateway
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest -f api-gateway/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

      - name: Build and Push user-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest -f user-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

      - name: Build and Push product-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service:latest -f product-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/product-service:latest

      - name: Build and Push order-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order-service:latest -f order-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/order-service:latest